import pyautogui
import time
import random

hacker_msgs = [
    "⚠️ Access Granted: Root Level",
    "💻 Injecting payload...",
    "🛡️ Bypassing firewall rules...",
    "🔓 Cracking credentials...",
    "📡 Connecting to C2 server...",
    "📁 Downloading confidential files...",
    "🧠 AI core compromised.",
    "⏳ Waiting for zero-day trigger...",
    "🔐 AES-256 encryption breached.",
    "🧬 DNA scan verified. Identity matched.",
    "📶 Signal traced to unknown source.",
    "📤 Uploading reverse shell...",
    "💥 Virus initiated: smile.exe",
    "🦠 Deploying worm to network...",
    "📲 Hijacking SMS gateway...",
    "🚨 ALERT: FBI tracing attempt blocked.",
    "🔁 Loop injection successful.",
    "📂 Rootkit embedded in kernel.",
    "⚙️ System DLL override complete.",
    "🎯 Target locked.",
    "☠️ Remote brainwave sync initialized.",
    "🌐 Tor node compromised.",
    "🎭 Identity spoofed: Anonymous mode ON.",
    "🌀 Matrix sync complete.",
    "🧊 Freezing RAM to dump content...",
    "🔍 Stealing browser passwords...",
    "📦 Installing keylogger...",
    "🗝️ Master password found.",
    "⚠️ Enabling Quantum backdoor...",
    "🕳️ Hole punched through NAT firewall.",
    "📡 WiFi router firmware replaced.",
    "🚫 Antivirus disabled.",
    "🖥️ Screen mirroring initiated.",
    "🕵️‍♂️ Webcam is now streaming...",
    "🧱 Encrypting system32...",
    "💿 Burning backup disks...",
    "🚀 Launching botnet attack...",
    "🪙 Mining crypto using your GPU...",
    "🧬 DNA mutated. Just kidding. Or not.",
    "💡 LED flicker pattern updated.",
    "🌌 Connecting to alien server...",
    "💤 Putting system into sleep-mode trap...",
    "🔄 Overclocking CPU to 9999%",
    "📲 Sending SMS to all contacts...",
    "💥 Boom.exe activated!",
    "🛑 System locked by Black Hat Syndicate.",
    "📛 BIOS rewrite in progress...",
    "🌈 Injecting colorful chaos...",
    "🥷 Ninja script deployed silently.",
    "💣 Self-destruct countdown: 3... 2... 1..."
        "[ILOVEYOU] - Rewriting all .jpg and .doc files...",
    "[MyDoom] - SMTP flood detected.",
    "[Stuxnet] - Target PLCs infected.",
    "[Melissa] - Infecting Word macros...",
    "[Blaster] - RPC exploit launched. Countdown started.",
    "[Sasser] - SYSTEM FAILURE: lsass.exe crashed.",
    "[CIH] - BIOS overwrite initiated.",
    "[WannaCry] - Ransom Note: Decryption key = $300 BTC.",
    "[CodeRed] - IIS server compromised.",
    "[SQL Slammer] - Database buffer overflowed.",
    "[CryptoLocker] - Your files have been encrypted.",
    "[Emotet] - Credential dumping in progress...",
    "[Pegasus] - Mobile device control enabled.",
    "[NotPetya] - MBR overwritten. System unstable.",
    "[TrickBot] - Internal network infected.",
    "[Zeus] - Banking info stolen.",
    "[DarkComet] - RAT session active.",
    "[LoveBug] - Email contacts harvested.",
    "[BlackEnergy] - ICS compromised.",
    "[Conficker] - Windows Update disabled.",
    
    "[GhostNet] - Intelligence data exfiltrated.",
    "[ShadowHammer] - Supply chain infection running...",
    "[FLUX] - Redirection protocol injected.",
    "[NightCrow] - SYSTEM integrity compromised.",
    "[0x666] - Error: USER_ROOT not found.",
    "[RedLine] - Exfiltrating browser credentials...",
    "[GOD Protocol] - File system locked.",
    "[Skynet] - You are now a node in the swarm.",
    "[Group-X] - Welcome to Phase Two.",
    "[BlackSun] - Kernel Panic... Rebooting reality.",
    "[EchoNine] - Backdoor persistence installed.",
    "[Binary Phantom] - Manifesting in memory.",
    "[Error 0xDEADBEEF] - Critical failure.",
    "[NullByte] - Memory leak exploited.",
    "[Bloodline] - Identity cloning initialized.",
    "[VoidWalker] - Shadow operations commenced.",
    "[#OpNebula] - Anonymous entry confirmed.",
    "[Specter] - Bypassing UAC silently.",
    "[RootHex] - System-level privilege escalated.",
    "[CrimsonLeak] - Full disk encryption triggered.",
    "[H4C-K3R] - No antivirus can stop us.",
    "[F4T3] - Welcome to the simulation.",
    "[CypherLock] - AES chain disruption started.",
    "[ReaperNet] - Humanity reset protocol ready.",
    "[Binary Sect] - Your secrets are public.",
    "[VIRUX] - Spread module running...",
    "[404VirusNotFound] - But it's already too late.",
    "[KernelCorrupt] - HAL.dll compromised.",
    "[Z3R0D4Y] - Exploit deployed successfully.",
    "[SYNFlood] - Packet storm in progress.",
    "[DeepVoid] - AI core injected..."
]

# زنجیره‌ی popupها:
for i in range(50):
    msg = hacker_msgs[i % len(hacker_msgs)]
    pyautogui.alert(msg, title=f"🔒 Hack Alert [{i+1}/50]")
    time.sleep(0.5)
